server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Documents/github/miri-miri-config

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, bean, httpexchanges, busrefresh