server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: user-login
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-auth
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/api/auth/**
            - Method=GET,POST,PATCH,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - JwtAuthorizationFilter

        - id: user-admin
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/api/admin/**
            - Method=GET,POST,PATCH,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - JwtAuthorizationFilter

        - id: user-internal
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/api/internal/**
            - Method=GET,POST,PATCH,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/api/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-actuator
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: goods-auth
          uri: lb://GOODS-SERVICE
          predicates:
            - Path=/goods-service/api/auth/**
            - Method=GET,POST,PATCH,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/goods-service/(?<segment>.*), /$\{segment}
            - JwtAuthorizationFilter

        - id: goods-admin
          uri: lb://GOODS-SERVICE
          predicates:
            - Path=/goods-service/api/admin/**
            - Method=GET,POST,PATCH,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/goods-service/(?<segment>.*), /$\{segment}
            - JwtAuthorizationFilter

        - id: goods-internal
          uri: lb://GOODS-SERVICE
          predicates:
            - Path=/goods-service/api/internal/**
            - Method=GET,POST,PATCH,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/goods-service/(?<segment>.*), /$\{segment}

        - id: goods-service
          uri: lb://GOODS-SERVICE
          predicates:
            - Path=/goods-service/api/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/goods-service/(?<segment>.*), /$\{segment}

        - id: goods-actuator
          uri: lb://GOODS-SERVICE
          predicates:
            - Path=/goods-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/goods-service/(?<segment>.*), /$\{segment}

        - id: order-auth
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/api/auth/**
            - Method=GET,POST,PATCH,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
            - JwtAuthorizationFilter

        - id: order-admin
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/api/admin/**
            - Method=GET,POST,PATCH,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
            - JwtAuthorizationFilter

        - id: order-internal
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/api/internal/**
            - Method=GET,POST,PATCH,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/api/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}

        - id: order-actuator
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httpexchanges, busrefresh