server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: goods-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    open-in-view: false
    properties:
      '[hibernate.default_batch_fetch_size]': 100
    hibernate:
      ddl-auto: update
  datasource:
#    url: jdbc:mariadb://goods_mariadb:3306/miri_user
#    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3310/miri_user
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ${database.password}

logging:
  level:
    com.miri.goodsservice: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httpexchanges, busrefresh