server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  profiles:
    include: secret
  application:
    name: order-service
  jpa:
    open-in-view: false
    properties:
      '[hibernate.default_batch_fetch_size]': 100
    hibernate:
      ddl-auto: update
  datasource:
#    url: jdbc:mariadb://order_mariadb:3306/miri_user
#    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3309/miri_user
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: mariadb1234
  data:
    redis:
#      host: user_redis
#      port: 6379
      host: localhost
      port: 6380
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${miri.mail.username}
    password: ${miri.mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true