server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  profiles:
    active: dev
  application:
    name: user-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    open-in-view: false
    properties:
      '[hibernate.default_batch_fetch_size]': 100
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mariadb://localhost:3308/miri_user?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ${database.password}
  data:
    redis:
      host: localhost
      port: 6380
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${miri.mail.username}
    password: ${miri.mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com.miri.userservice: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httpexchanges, busrefresh